const Languages = Object.freeze({
    ABAP: "abap",
    Agda: "agda",
    Arduino: "arduino",
    ASCII_Art: "ascii art",
    Assembly: "assembly",
    Bash: "bash",
    BASIC: "basic",
    BNF: "bnf",
    C: "c",
    CSharp: "c#",
    Cpp: "c++",
    Clojure: "clojure",
    CoffeeScript: "coffeescript",
    CSS: "css",
    Dart: "dart",
    Dhall: "dhall",
    Diff: "diff",
    Docker: "docker",
    EBNF: "ebnf",
    Elixir: "elixir",
    Elm: "elm",
    Erlang: "erlang",
    FSharp: "f#",
    Flow: "flow",
    Fortan: "fortran",
    Gherkin: "gherkin",
    GLSL: "glsl",
    Go: "go",
    GraphQL: "graphql",
    Groovy: "groovy",
    Haskell: "haskell",
    HCL: "hcl",
    HTML: "html",
    Idris: "idris",
    Java: "java",
    JavaScript: "javascript",
    JSON: "json",
    Julia: "julia",
    Kotlin: "kotlin",
    LaTeX: "latex",
    Less: "less",
    Lisp: "lisp",
    LiveScript: "livescript",
    LLVM_IR: "llvm ir",
    Lua: "lua",
    Makefile: "makefile",
    Markdown: "markdown",
    Markup: "markup",
    Mathematica: "mathematica",
    MATLAB: "matlab",
    Mermaid: "mermaid",
    Nix: "nix",
    Notion_Formula: "notion formula",
    Objectiv_C: "objective-c",
    OCaml: "ocaml",
    Pascal: "pascal",
    Perl: "perl",
    PHP: "php",
    Plain_Text: "plain text",
    PowerShell: "powershell",
    Prolog: "prolog",
    Protobuf: "protobuf",
    PureScript: "purescript",
    Python: "python",
    R: "r",
    Racket: "racket",
    Reason: "reason",
    Rocq: "coq",
    Ruby: "ruby",
    Rust: "rust",
    Sass: "sass",
    Scala: "scala",
    Scheme: "scheme",
    SCSS: "scss",
    Shell: "shell",
    Smalltalk: "smalltalk",
    Solidity: "sql",
    SQL: "sql",
    Swift: "swift",
    TOML: "toml",
    TypeScript: "typescript",
    VBNet: "vb.net",
    Verilog: "verilog",
    VHDL: "vhdl",
    Visual_Basic: "visual basic",
    WebAssembly: "webassembly",
    XML: "xml",
    YAML: "yaml",
})

export default Languages;